# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr
  contentDir: content/fr
  title: Pierrick Le Vourc'h
  params:
    description: Description en français
  menu:
     main:
      - name: Accueil et contact
        url: '#apropos'
        weight: 10
      - name: Publications
        url: 'fr/publications'
        weight: 20
      - name: Enseignements
        url: 'enseignements'
        weight: 30
      - name: Exposés
        url: '#exposes'
        weight: 40
      - name: Documents
        url: 'fr/documents'
        weight: 50
