# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
fr:
  languageCode: fr
  contentDir: content/fr
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Pierrick Le Vourc'h
  params:
    description: English description
  menu:
    main:
      - name: Home and contact
        url: '#about'
       weight: 10
      - name: Publications
        url: publications/
        weight: 20
      - name: Teaching
        url: teaching/
        weight: 30
      - name: Talks
        url: talks/
        weight: 40
      - name: Documents
        url: documents/
        weight: 50
      